#!/bin/bash

if [ ! -d "$1" ]
    then
    echo "usage: $0 <dataset-path>"
    exit 1
fi

DPATH="$1"
source config

$LEARN mf5 ori
# $LEARN mf5 gau
# $LEARN mf5 res
# $LEARN mf5 ave

$LEARN mf3 ori
# $LEARN mf3 gau
# $LEARN mf3 res
# $LEARN mf3 ave


$LEARN mf35     ori
$LEARN mf35-64  ori-64
$LEARN mf35-256 ori-256
# $LEARN mf35     all
# $LEARN mf35-64  all-64
# $LEARN mf35-256 all-256
