#!/bin/bash

if [ ! -d "$1" ]
    then
    echo "usage: $0 <dataset-path>"
    exit 1
fi

DPATH="$1"

source config
TEST="python median_traces.py test -p $DPATH "
MEASURE_PSNR="python median_traces.py measure psnr -r $PATTERN_TEST "

do_test()
{
    a="$1"
    b="$2"
    t="$3"

    anti_dir="$DPATH/anti-testcases/$a-$t-$4.$5/"
    anti_tests="$anti_dir/$PATTERN_TEST"
    filt_tests="$DPATH/$b/$PATTERN_TEST"
    mfdir="$DPATH/$a"

    accuracy=$($TEST $a $b $anti_tests $filt_tests)
    psnr=$($MEASURE_PSNR $mfdir $anti_dir | cut -d ' ' -f 1)
    #ssim=$($MEASURE ssim $mfdir $antidir | cut -d ' ' -f 1)
    printf "$a\t$b\t$t\t[$range]\t$accuracy\t$psnr\t$ssim\n"
}

printf "MEDIAN\tFILTER\tTHRESHOLD\tNOISE\tACCURACY\tPSNR\n"
for t in $THRESHOLDS; do
    for range in "${NOISE_RANGES[@]}"; do
        do_test mf3      ori     $t $range
        do_test mf3      gau     $t $range
        do_test mf3      res     $t $range
        do_test mf3      ave     $t $range
        do_test mf5      ori     $t $range
        do_test mf5      gau     $t $range
        do_test mf5      res     $t $range
        do_test mf5      ave     $t $range
        do_test mf35     ori     $t $range
        do_test mf35     all     $t $range


        do_test mf3-64      ori-64     $t $range
        do_test mf3-64      gau-64     $t $range
        do_test mf3-64      res-64     $t $range
        do_test mf3-64      ave-64     $t $range
        do_test mf5-64      ori-64     $t $range
        do_test mf5-64      gau-64     $t $range
        do_test mf5-64      res-64     $t $range
        do_test mf5-64      ave-64     $t $range
        do_test mf35-64     ori-64     $t $range
        do_test mf35-64     all-64     $t $range

        do_test mf3-256      ori-256     $t $range
        do_test mf3-256      gau-256     $t $range
        do_test mf3-256      res-256     $t $range
        do_test mf3-256      ave-256     $t $range
        do_test mf5-256      ori-256     $t $range
        do_test mf5-256      gau-256     $t $range
        do_test mf5-256      res-256     $t $range
        do_test mf5-256      ave-256     $t $range
        do_test mf35-256     ori-256     $t $range
        do_test mf35-256     all-256     $t $range



    done
done
