#!/bin/bash

if [ ! -d "$1" ]
    then
    echo "usage: $0 <dataset-path>"
    exit 1
fi

DPATH="$1"

source config
TEST="python median_traces.py test   --path=$DPATH  --regex $PATTERN_TEST "
MEASURE="python median_traces.py measure psnr"

do_test()
{
    a="$1"
    b="$2"

    antidir="$DPATH/anti-testcases/$a-$t-[$3-$4]/"
	mfdir="$DPATH/$a"

    accuracy=$($TEST $a $b --cls $a $antidir)
	psnr=$($MEASURE psnr $mfdir $antidir | cut -d ' ' -f 1)
	#ssim=$($MEASURE ssim $mfdir $antidir | cut -d ' ' -f 1)
	printf "$a\t$t\t\[$range\]\t$accuracy\t$psnr\t$ssim\n"
}


for t in $THRESHOLDS; do
    for range in "${NOISE_RANGES[@]}"; do
        do_test mf3      ori     $t $range
        do_test mf5      ori     $t $range
        do_test mf35     ori     $t $range
        do_test mf35-64  ori-64  $t $range
        do_test mf35-256 ori-256 $t $range
    done
done
